import { Promises } from "@/components/promises";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SessionProvider } from "@/providers/SessionProvider";
import { getServerSession } from "next-auth";
import { authOptionsFirebase } from "@/lib/auth";
import { SignIn } from "@/components/SignIn";
import { Dashboard } from "@/components/Dashboard";
import Home from "./page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptionsFirebase);

  return (
    <html lang="en" className="bg-zinc-900 text-zinc-50">
      <body className={inter.className}>
        <SessionProvider session={session}>
          {!session ? <SignIn /> : <Home />}
        </SessionProvider>
      </body>
    </html>
  );
}
