import { Promises } from "@/components/promises";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-zinc-900 text-zinc-50">
      <body className={inter.className}>
        {children}
        {/* <Promises>{children}</Promises> */}
      </body>
    </html>
  );
}
